### ISSUE TITLE
typo et erreur dans le TP Arduino

### ISSUE THREAD

**Issue by simonbasle** [Devoxx4KidsFR/materials#3]
Hello @cfalguiere,
J'ai relevé une lettre manquante et ce que je pense être une erreur dans deux des fiches de l'atelier Arduino:

[PR10](https://github.com/Devoxx4KidsFR/materials/blob/master/ateliers/arduino/00-Presentations/PR10-bits%20et%20base%202.pdf): dans la section "convertir de base 2 en base 10", `puis 2 (2x4)` devrait être `puis `**8**` (2x4)` non?

[FL03](https://github.com/Devoxx4KidsFR/materials/blob/master/ateliers/arduino/01-Facile/FL03-Interface%20Old%20School/FL03-Interface%20Old%20School.pdf): `onction` au lieu de **f**`onction`

**Comment by cfalguiere** [comment]
Bonjour Simon,

Merci pour la relecture.
C'est corrigé.

A bientôt
Claude
